#!/bin/bash

# Configuration
APP_NAME="HolyReminder"
BUILD_DIR=".build/release"
APP_BUNDLE="${APP_NAME}.app"
OUTPUT_DIR="build/Export"

echo "🚀 Starting Release Build for ${APP_NAME}..."

# 1. Clean and Build
echo "🧹 Cleaning..."
rm -rf ".build"
rm -rf "build"

echo "🔨 Building with Swift PM..."
swift build -c release

if [ $? -ne 0 ]; then
    echo "❌ Build failed."
    exit 1
fi

# 2. Create App Bundle Structure
echo "📦 Creating App Bundle..."
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}/${APP_BUNDLE}/Contents/MacOS"
mkdir -p "${OUTPUT_DIR}/${APP_BUNDLE}/Contents/Resources"

# 3. Copy Binary
echo "� Copying Binary..."
# Check for universal binary or specific arch. `swift build --arch ...` creates universal in apple-universal if multiple?
# Or just copy from the release dir.
# Since we used --arch twice, it might be in apple-universal/release/HolyReminder
if [ -f ".build/apple/Products/Release/HolyReminder" ]; then
    cp ".build/apple/Products/Release/HolyReminder" "${OUTPUT_DIR}/${APP_BUNDLE}/Contents/MacOS/"
elif [ -f ".build/release/HolyReminder" ]; then
    cp ".build/release/HolyReminder" "${OUTPUT_DIR}/${APP_BUNDLE}/Contents/MacOS/"
else
    # Fallback to finding it
    BINARY=$(find .build -name HolyReminder -type f | grep "release" | head -n 1)
    if [ -z "$BINARY" ]; then
        echo "❌ Could not find compiled binary."
        exit 1
    fi
    cp "$BINARY" "${OUTPUT_DIR}/${APP_BUNDLE}/Contents/MacOS/"
fi

# 4. Copy Info.plist
echo "📝 Copying Info.plist..."
if [ -f "Info.plist" ]; then
    cp "Info.plist" "${OUTPUT_DIR}/${APP_BUNDLE}/Contents/Info.plist"
else
    echo "❌ Info.plist not found!"
    exit 1
fi

# 5. Copy Resources
echo "🎨 Copying Resources..."
# Copy AppIcon
if [ -f "Sources/HolyReminder/Resources/AppIcon.icns" ]; then
    cp "Sources/HolyReminder/Resources/AppIcon.icns" "${OUTPUT_DIR}/${APP_BUNDLE}/Contents/Resources/"
fi

# Copy verses.json
if [ -f "Sources/HolyReminder/Resources/verses.json" ]; then
    cp "Sources/HolyReminder/Resources/verses.json" "${OUTPUT_DIR}/${APP_BUNDLE}/Contents/Resources/"
fi

# Create Bundle.module support (HolyReminder_HolyReminder.bundle)
# SPM usually expects this bundle to exist if resources are processed.
RESOURCE_BUNDLE="${OUTPUT_DIR}/${APP_BUNDLE}/Contents/Resources/${APP_NAME}_${APP_NAME}.bundle"
mkdir -p "$RESOURCE_BUNDLE"
cp "Sources/HolyReminder/Resources/verses.json" "$RESOURCE_BUNDLE/"
# Copy Info.plist into bundle if needed (usually generated by SPM) but we can simulate it or skip if not strictly checked.
# But better to just put resources in Contents/Resources and hope the main bundle lookup finds it, 
# OR put the bundle in Contents/Resources.
# A common trick for SPM apps is to create the bundle structure inside Resources.

# 6. Sign the App
echo "🔐 Signing App Bundle skipped (relying on binary signature)..."
# xattr -cr "${OUTPUT_DIR}/${APP_BUNDLE}"
# codesign --force --deep --sign - "${OUTPUT_DIR}/${APP_BUNDLE}"

# if [ $? -ne 0 ]; then
#     echo "❌ Code signing failed."
#     exit 1
# fi

# 7. Create DMG
echo "📀 Creating DMG..."
cd "${OUTPUT_DIR}"

# Create a temporary folder for DMG contents
DMG_TEMP="dmg_temp"
rm -rf "$DMG_TEMP"
mkdir -p "$DMG_TEMP"

# Copy app to temp folder
cp -R "${APP_BUNDLE}" "$DMG_TEMP/"

# Create symlink to Applications folder
ln -s /Applications "$DMG_TEMP/Applications"

# Create DMG
DMG_NAME="${APP_NAME}.dmg"
rm -f "$DMG_NAME"

hdiutil create -volname "${APP_NAME}" -srcfolder "$DMG_TEMP" -ov -format UDZO "$DMG_NAME" > /dev/null

# Cleanup
rm -rf "$DMG_TEMP"

# Also create ZIP as backup
echo "🤐 Creating backup ZIP..."
zip -r "${APP_NAME}.zip" "${APP_BUNDLE}" > /dev/null

echo "✅ Build complete!"
echo "📀 DMG: ${OUTPUT_DIR}/${APP_NAME}.dmg"
echo "🤐 ZIP: ${OUTPUT_DIR}/${APP_NAME}.zip"

# Open Finder
open .
